### ISSUE TITLE
Multiple instances of component?

### ISSUE THREAD

**Issue by smeranda** [sebastiandedeyne/code-splitting-with-laravel-mix#2]
How would you update this to support multiple instances of a component? For example, I'm loading a video player component on a page multiple times. Instead of using `getElementById`, I've switched to `getElementByClassName`:

```js
if (document.getElementsByClassName("c-video--vimeo-vue")) {
    import('./initVimeo' /* webpackChunkName: "js/video" */)
        .then(initVimeo => {
            initVimeo.default()
        }
    )
}
```

However, it only runs on the first instance? Nothing happens for the second instance in DOM.

```js
// file initVimeo.js

import vueVimeoPlayer from 'vue-vimeo-player'
import Vue from 'vue'

Vue.use(vueVimeoPlayer)

Vue.component('video-player', require('./components/VideoVimeoPlayer.vue'))

export default function () {
    new Vue({
        store,
        el: '.c-video--vimeo-vue'
    });
}
```

**Comment by sebastiandedeyne** [comment]
Hi @smeranda,

By using `el: '.c-video--vimeo-vue'`, Vue will look for the first occurrence of `.c-video--vimeo-vue` and mount on that element.

What you're looking for is to mount on every occurrence of `.c-video--vimeo-vue`, so you'll need to loop over them.

```js
export default function () {
    [...document.getElementsByClassName("c-video--vimeo-vue")].forEach(el => {    
        new Vue({ store, el });
    });
}
```

**Comment by smeranda** [comment]
Brilliant, thank you.
